#!/usr/bin/env bash
# Install nginx on my web01 server
# Nginx should be listening on port 80
# When sent a GET request at root, return a page that contains
# one string "Hello World"

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
