#!/usr/bin/env bash
# redirect me.
sudo -s apt-get update && sudo -s apt-get install nginx -y

echo "Hello World" > /var/www/html/index.nginx-debian.html

found="server_name _;"
adding="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}"
sudo sed -i "/$found/a\\$adding" /etc/nginx/sites-available/default
sudo -s service nginx restart
