#!/usr/bin/env bash
# redirect me.
apt-get update && apt-get install nginx -y

echo "Hello World" > /var/www/html/index.nginx-debian.html

found="server_name _;"
adding="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}"
sed -i "/$found/a\\$adding" /etc/nginx/sites-available/default
service nginx restart
