#!/usr/bin/env bash
# NOT FOUND - PAGE 404
apt-get update && apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

found="server_name _;"
adding="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtube.com/clip/UgkxdTtNavadjDHXvbahamufHluS4ZkB1y2K;\n\t}"
sed -i "/$found/a\\$adding" /etc/nginx/sites-available/default


adding="\n\terror_page 404 /error_404.html;"
sed -i "/$found/a\\$adding" /etc/nginx/sites-available/default

service nginx restart