#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo 'Hello World' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo sed -i '/server_name _;/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; }' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a error_page 404 /error_404.html;\nlocation = /error_404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a add_header X-Served-By ${HOSTNAME};" /etc/nginx/sites-available/default
sudo service nginx restart
