#!/usr/bin/env bash
# # Configure Nginx so that its HTTP response contains a custom header

sudo apt-get update -y
apt-get -y upgrade
sudo apt-get install -y nginx

echo "Hello World" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sed -i "/server_name _;/a error_page 404 /error_404.html;\nlocation = /error_404.html {\nroot /var/www/html;\ninternal;\n}" /etc/nginx/sites-available/default
sed -i "/server_name _;/a add_header X-Served-By $HOSTNAMEhostname;" /etc/nginx/sites-available/default

sudo service nginx restart
