#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Admin web-01 and web-02
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8

sudo apt-get -y update
sudo apt-get install -y haproxy
