#!/usr/bin/env bash
# installing firewall

sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing
# sudo ufw allow 22
# sudo ufw allow 443
# sudo ufw allow 80
sudo ufw enable -y



# These commands set the defaults for denying incoming
# connections and allowing outgoing connections.

sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
